---
# FD Spec
apiVersion: apps.tess.io/v1alpha3
kind: FederatedDeployment
metadata:
  name: helloworld-fd
  namespace: helloworld
spec:
  applicationInstanceRef:
    kind: ApplicationInstance
    name: placement-app-instance # Name must be valid Application Instance in the FCP
    namespace: helloworld
  # A TFD specification comprises of an array called deployments.
  # The first and most important one is the FCP deployment 
  # The name "fcp" referes to Federated Control Plane. DO NOT CHANGE the value.  
  # NOTE - In future we would provide the reasons as to why this field is an Array.
  deployments:
  - name: fcp
    # Refers to the fact that this TFD is created at a Global scope.
    # Permissible scopes are "Global, Cluster"
    # Purpose of this field is to ensure there is a "Supervisor" governing this TFD
    type: Global
    strategy:
      # The "base" here refers to the Basic Deployment Template in Kubernetes
      base:
        replicas: 2 # Total count of replicas across all K8s clusters
        template:
          metadata:
            annotations:
              # Refer to Exposing Deployments in tess.io 
              rollout.deployment.tess.io/lb_sync_strategy: '["svca"]'        
              rollout.deployment.k8s.io/wait-for-lb-sync: "true" 
          spec:
            selector:
              matchLabels:
                applicationinstance.tess.io/name: placement-app-instance
            strategy:
              rollingUpdate:
                maxSurge: 25%
                maxUnavailable: 25%
              type: RollingUpdate
            template:
              metadata:
                labels:
                  applicationinstance.tess.io/name: placement-app-instance
              spec:
                containers:
                - image: hub.tess.io/tessio/nginx:latest
                  imagePullPolicy: Always
                  name: tessapp
      # Refers to where your workload shall have to be placed in the many K8s clusters supported by Tess
      placement:
       # Field `clusterSelector` lets the FD user declare placement 
       # based on selections.
        clusterSelector:
         # Ensures that the Federated Deployment is placed ONLY on K8s clusters matching the label selector
         # NOTE - The K8s clusters defined in the Cluster Registry with following label alone with be members for this fdv1alpha3
         # In this example this label refers to list of K8s clusters suporting the "environment" by name "feature"
         matchLabels:
           cluster.cr.tess.io/env-feature: true
        # Ensures only TWO of the total set of clusters matching the label above shall be selected to place this tfd
        maxClusterCount: 2
      rollout:
        rollingUpdate:
          # Ensures ONLY one of the "2" clusters get the changes (if and when made)
          maxUnavailable: 1
        type: RollingUpdate
      supervisor:
        tiers:
        - Global
        - Cluster
        type: Global
  # Ensures upto TEN revision changes of the TFD are preserved at the FCP
  revisionHistoryLimit: 10